name: Daily Summary

on:
  schedule:
    - cron: '0 11 * * *'  # Every day at 11:00 UTC
  workflow_dispatch:

jobs:
  generate-summary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Update CA certificates
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo update-ca-certificates

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Python SSL variables
      run: |
        echo "PYTHONHTTPSVERIFY=1" >> $GITHUB_ENV
        echo "SSL_CERT_FILE=$(python -c 'import certifi; print(certifi.where())')" >> $GITHUB_ENV
        echo "REQUESTS_CA_BUNDLE=$(python -c 'import certifi; print(certifi.where())')" >> $GITHUB_ENV

    - name: Run summary generator
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
        TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
      run: |
        python ai_summary_agent.py
