name: Daily Summary

on:
  schedule:
    - cron: '0 16 * * *'  # Every day at 16:00 UTC
  workflow_dispatch:

jobs:
  generate-summary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install certifi

    - name: Run scraper / summary generator
      run: |
        python scrape.py  # or whatever script you're using
