name: Daily Summary

on:
  schedule:
    - cron: '0 16 * * *'  # Every day at 16:00 UTC
  workflow_dispatch:

jobs:
  generate-summary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Upgrade system CA certificates
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates
        sudo update-ca-certificates

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install certifi
        export SSL_CERT_FILE=$(python -m certifi)
        pip install -r requirements.txt

    - name: Run scraper / summary generator
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SSL_CERT_FILE: $(python -m certifi)
      run: |
        python ai_summary_agent.py
